// Code generated by MockGen. DO NOT EDIT.
// Source: sbom_step.go
//
// Generated by this command:
//
//	mockgen -source sbom_step.go -package mock -destination ../../test/mock/bom_patcher.go -mock_names BOMPatcherInterface=MockBOMPatcher
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	cyclonedx "github.com/CycloneDX/cyclonedx-go"
	gomock "go.uber.org/mock/gomock"
)

// MockBOMPatcher is a mock of BOMPatcherInterface interface.
type MockBOMPatcher struct {
	ctrl     *gomock.Controller
	recorder *MockBOMPatcherMockRecorder
	isgomock struct{}
}

// MockBOMPatcherMockRecorder is the mock recorder for MockBOMPatcher.
type MockBOMPatcherMockRecorder struct {
	mock *MockBOMPatcher
}

// NewMockBOMPatcher creates a new mock instance.
func NewMockBOMPatcher(ctrl *gomock.Controller) *MockBOMPatcher {
	mock := &MockBOMPatcher{ctrl: ctrl}
	mock.recorder = &MockBOMPatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBOMPatcher) EXPECT() *MockBOMPatcherMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockBOMPatcher) Apply(ctx context.Context, bom *cyclonedx.BOM) (*cyclonedx.BOM, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, bom)
	ret0, _ := ret[0].(*cyclonedx.BOM)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockBOMPatcherMockRecorder) Apply(ctx, bom any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockBOMPatcher)(nil).Apply), ctx, bom)
}
