// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source repo.go -package mock -destination ../../test/mock/includes_repo.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	git "github.com/go-git/go-git/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockGitRepository is a mock of GitRepository interface.
type MockGitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGitRepositoryMockRecorder
	isgomock struct{}
}

// MockGitRepositoryMockRecorder is the mock recorder for MockGitRepository.
type MockGitRepositoryMockRecorder struct {
	mock *MockGitRepository
}

// NewMockGitRepository creates a new mock instance.
func NewMockGitRepository(ctrl *gomock.Controller) *MockGitRepository {
	mock := &MockGitRepository{ctrl: ctrl}
	mock.recorder = &MockGitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitRepository) EXPECT() *MockGitRepositoryMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockGitRepository) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockGitRepositoryMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockGitRepository)(nil).GetName))
}

// IsCommitDirectoryExist mocks base method.
func (m *MockGitRepository) IsCommitDirectoryExist(ctx context.Context, commit, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCommitDirectoryExist", ctx, commit, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCommitDirectoryExist indicates an expected call of IsCommitDirectoryExist.
func (mr *MockGitRepositoryMockRecorder) IsCommitDirectoryExist(ctx, commit, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCommitDirectoryExist", reflect.TypeOf((*MockGitRepository)(nil).IsCommitDirectoryExist), ctx, commit, path)
}

// IsCommitFileExist mocks base method.
func (m *MockGitRepository) IsCommitFileExist(ctx context.Context, commit, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCommitFileExist", ctx, commit, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCommitFileExist indicates an expected call of IsCommitFileExist.
func (mr *MockGitRepositoryMockRecorder) IsCommitFileExist(ctx, commit, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCommitFileExist", reflect.TypeOf((*MockGitRepository)(nil).IsCommitFileExist), ctx, commit, path)
}

// PlainOpen mocks base method.
func (m *MockGitRepository) PlainOpen() (*git.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlainOpen")
	ret0, _ := ret[0].(*git.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlainOpen indicates an expected call of PlainOpen.
func (mr *MockGitRepositoryMockRecorder) PlainOpen() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlainOpen", reflect.TypeOf((*MockGitRepository)(nil).PlainOpen))
}

// ReadCommitFile mocks base method.
func (m *MockGitRepository) ReadCommitFile(ctx context.Context, commit, path string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadCommitFile", ctx, commit, path)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadCommitFile indicates an expected call of ReadCommitFile.
func (mr *MockGitRepositoryMockRecorder) ReadCommitFile(ctx, commit, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadCommitFile", reflect.TypeOf((*MockGitRepository)(nil).ReadCommitFile), ctx, commit, path)
}
