// Code generated by MockGen. DO NOT EDIT.
// Source: legacy_interface.go
//
// Generated by this command:
//
//	mockgen -source legacy_interface.go -package mock -destination ../../test/mock/legacy_interface.go
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	container_backend "github.com/werf/werf/v2/pkg/container_backend"
	image "github.com/werf/werf/v2/pkg/image"
	gomock "go.uber.org/mock/gomock"
)

// MockLegacyImageInterface is a mock of LegacyImageInterface interface.
type MockLegacyImageInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLegacyImageInterfaceMockRecorder
	isgomock struct{}
}

// MockLegacyImageInterfaceMockRecorder is the mock recorder for MockLegacyImageInterface.
type MockLegacyImageInterfaceMockRecorder struct {
	mock *MockLegacyImageInterface
}

// NewMockLegacyImageInterface creates a new mock instance.
func NewMockLegacyImageInterface(ctrl *gomock.Controller) *MockLegacyImageInterface {
	mock := &MockLegacyImageInterface{ctrl: ctrl}
	mock.recorder = &MockLegacyImageInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLegacyImageInterface) EXPECT() *MockLegacyImageInterfaceMockRecorder {
	return m.recorder
}

// BuiltID mocks base method.
func (m *MockLegacyImageInterface) BuiltID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuiltID")
	ret0, _ := ret[0].(string)
	return ret0
}

// BuiltID indicates an expected call of BuiltID.
func (mr *MockLegacyImageInterfaceMockRecorder) BuiltID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuiltID", reflect.TypeOf((*MockLegacyImageInterface)(nil).BuiltID))
}

// GetBuildServiceLabels mocks base method.
func (m *MockLegacyImageInterface) GetBuildServiceLabels() map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBuildServiceLabels")
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// GetBuildServiceLabels indicates an expected call of GetBuildServiceLabels.
func (mr *MockLegacyImageInterfaceMockRecorder) GetBuildServiceLabels() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBuildServiceLabels", reflect.TypeOf((*MockLegacyImageInterface)(nil).GetBuildServiceLabels))
}

// GetCopy mocks base method.
func (m *MockLegacyImageInterface) GetCopy() container_backend.LegacyImageInterface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCopy")
	ret0, _ := ret[0].(container_backend.LegacyImageInterface)
	return ret0
}

// GetCopy indicates an expected call of GetCopy.
func (mr *MockLegacyImageInterfaceMockRecorder) GetCopy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCopy", reflect.TypeOf((*MockLegacyImageInterface)(nil).GetCopy))
}

// GetFinalStageDesc mocks base method.
func (m *MockLegacyImageInterface) GetFinalStageDesc() *image.StageDesc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFinalStageDesc")
	ret0, _ := ret[0].(*image.StageDesc)
	return ret0
}

// GetFinalStageDesc indicates an expected call of GetFinalStageDesc.
func (mr *MockLegacyImageInterfaceMockRecorder) GetFinalStageDesc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFinalStageDesc", reflect.TypeOf((*MockLegacyImageInterface)(nil).GetFinalStageDesc))
}

// GetStageDesc mocks base method.
func (m *MockLegacyImageInterface) GetStageDesc() *image.StageDesc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStageDesc")
	ret0, _ := ret[0].(*image.StageDesc)
	return ret0
}

// GetStageDesc indicates an expected call of GetStageDesc.
func (mr *MockLegacyImageInterfaceMockRecorder) GetStageDesc() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStageDesc", reflect.TypeOf((*MockLegacyImageInterface)(nil).GetStageDesc))
}

// GetTargetPlatform mocks base method.
func (m *MockLegacyImageInterface) GetTargetPlatform() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetPlatform")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTargetPlatform indicates an expected call of GetTargetPlatform.
func (mr *MockLegacyImageInterfaceMockRecorder) GetTargetPlatform() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetPlatform", reflect.TypeOf((*MockLegacyImageInterface)(nil).GetTargetPlatform))
}

// IsExistsLocally mocks base method.
func (m *MockLegacyImageInterface) IsExistsLocally() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsExistsLocally")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsExistsLocally indicates an expected call of IsExistsLocally.
func (mr *MockLegacyImageInterfaceMockRecorder) IsExistsLocally() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsExistsLocally", reflect.TypeOf((*MockLegacyImageInterface)(nil).IsExistsLocally))
}

// Name mocks base method.
func (m *MockLegacyImageInterface) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockLegacyImageInterfaceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockLegacyImageInterface)(nil).Name))
}

// Pull mocks base method.
func (m *MockLegacyImageInterface) Pull(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pull indicates an expected call of Pull.
func (mr *MockLegacyImageInterfaceMockRecorder) Pull(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockLegacyImageInterface)(nil).Pull), ctx)
}

// Push mocks base method.
func (m *MockLegacyImageInterface) Push(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockLegacyImageInterfaceMockRecorder) Push(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockLegacyImageInterface)(nil).Push), ctx)
}

// SetBuildServiceLabels mocks base method.
func (m *MockLegacyImageInterface) SetBuildServiceLabels(labels map[string]string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBuildServiceLabels", labels)
}

// SetBuildServiceLabels indicates an expected call of SetBuildServiceLabels.
func (mr *MockLegacyImageInterfaceMockRecorder) SetBuildServiceLabels(labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBuildServiceLabels", reflect.TypeOf((*MockLegacyImageInterface)(nil).SetBuildServiceLabels), labels)
}

// SetBuiltID mocks base method.
func (m *MockLegacyImageInterface) SetBuiltID(builtID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBuiltID", builtID)
}

// SetBuiltID indicates an expected call of SetBuiltID.
func (mr *MockLegacyImageInterfaceMockRecorder) SetBuiltID(builtID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBuiltID", reflect.TypeOf((*MockLegacyImageInterface)(nil).SetBuiltID), builtID)
}

// SetFinalStageDesc mocks base method.
func (m *MockLegacyImageInterface) SetFinalStageDesc(arg0 *image.StageDesc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFinalStageDesc", arg0)
}

// SetFinalStageDesc indicates an expected call of SetFinalStageDesc.
func (mr *MockLegacyImageInterfaceMockRecorder) SetFinalStageDesc(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFinalStageDesc", reflect.TypeOf((*MockLegacyImageInterface)(nil).SetFinalStageDesc), arg0)
}

// SetInfo mocks base method.
func (m *MockLegacyImageInterface) SetInfo(info *image.Info) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInfo", info)
}

// SetInfo indicates an expected call of SetInfo.
func (mr *MockLegacyImageInterfaceMockRecorder) SetInfo(info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInfo", reflect.TypeOf((*MockLegacyImageInterface)(nil).SetInfo), info)
}

// SetName mocks base method.
func (m *MockLegacyImageInterface) SetName(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetName", name)
}

// SetName indicates an expected call of SetName.
func (mr *MockLegacyImageInterfaceMockRecorder) SetName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetName", reflect.TypeOf((*MockLegacyImageInterface)(nil).SetName), name)
}

// SetStageDesc mocks base method.
func (m *MockLegacyImageInterface) SetStageDesc(arg0 *image.StageDesc) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStageDesc", arg0)
}

// SetStageDesc indicates an expected call of SetStageDesc.
func (mr *MockLegacyImageInterfaceMockRecorder) SetStageDesc(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStageDesc", reflect.TypeOf((*MockLegacyImageInterface)(nil).SetStageDesc), arg0)
}
