name "werf-stapel"

license "Apache 2.0"
license_file "LICENSE"

dependency "termcap"
dependency "bash"
dependency "gtar"
dependency "sudo"
dependency "coreutils"
dependency "findutils"
dependency "diffutils"
dependency "sed"
dependency "rsync"
dependency "shadow"
dependency "patch"
dependency "e2fsprogs"
dependency "file"
dependency "git"
dependency "ansible"
dependency "unzip"
