{{- $refs := list $.Values.global.github_ref }}

{{- range $_, $ref := $refs }}

{{- $sourceRef := splitList "/" $ref | last }}
{{- $isPrimaryDeployRef := eq $ref $.Values.global.github_ref }}
{{- $deployTarget := $sourceRef }}
{{- if and $isPrimaryDeployRef $.Values.global.docs_deploy_target }}
{{- $deployTarget = $.Values.global.docs_deploy_target }}
{{- end }}
{{- $deployTargetDNSNormalized := printf "%s" $deployTarget | lower | replace "+" "-plus-" | replace "_" "-u-" | replace "." "-dot-" }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
  annotations:
    "werf.io/replicas-on-creation": "1"
  labels:
    service: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      service: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
  template:
    metadata:
      labels:
        service: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
    spec:
      imagePullSecrets:
        - name: github-werfio
      priorityClassName: {{ pluck $.Values.werf.env $.Values.priorityClassName | first | default $.Values.priorityClassName._default }}
{{- include "clusterPlacement" $ | indent 6 }}
      containers:
        - name: web
          command: ["nginx", "-g", "daemon off;"]
          image: {{ index $.Values.werf.image "web" }}
{{- include "resources" $ | indent 10 }}
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
spec:
  clusterIP: None
  selector:
    service: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
  updatePolicy:
    updateMode: "Initial"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      service: {{ $.Chart.Name }}-{{ $deployTargetDNSNormalized }}
{{- end }}
