{{- $refs := list $.Values.global.github_ref }}
{{- if eq $.Values.werf.env "test" }}
{{- if eq (splitList "/" $.Values.global.github_ref | last) "main" }}
{{- $refs = concat $refs (list "v2" "v1.2") }}
{{- end }}
{{- end }}

{{- range $_, $ref := $refs }}

{{- $version := splitList "/" $ref | last }}
{{- if hasPrefix "v2" $version }}
{{- $version = "v2" }}
{{- else if hasPrefix "v1.2" $version }}
{{- $version = "v1.2" }}
{{- end }}
{{- $versionDNSNormalized := replace "." "-dot-" $version }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
  annotations:
    "werf.io/replicas-on-creation": "1"
  labels:
    service: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
spec:
  minReadySeconds: 5
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      service: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
  template:
    metadata:
      labels:
        service: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
    spec:
      imagePullSecrets:
        - name: github-werfio
      priorityClassName: {{ pluck $.Values.werf.env $.Values.priorityClassName | first | default $.Values.priorityClassName._default }}
{{- include "clusterPlacement" $ | indent 6 }}
      containers:
        - name: web
          command: ["nginx", "-g", "daemon off;"]
          image: {{ index $.Values.werf.image "web" }}
{{- include "resources" $ | indent 10 }}
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
spec:
  clusterIP: None
  selector:
    service: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
  ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
  updatePolicy:
    updateMode: "Initial"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      service: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
{{- end }}
