{{- $refs := list $.Values.global.github_ref }}
{{- if eq $.Values.werf.env "test" }}
{{- $currentRef := splitList "/" $.Values.global.github_ref | last }}
{{- if or (eq $currentRef "main") (hasPrefix "pr-" $currentRef) }}
{{- $refs = concat $refs (list "v2" "v1.2") }}
{{- end }}
{{- end }}

{{- range $_, $ref := $refs }}

{{- $version := splitList "/" $ref | last }}
{{- if hasPrefix "v2" $version }}
{{- $version = "v2" }}
{{- else if hasPrefix "v1.2" $version }}
{{- $version = "v1.2" }}
{{- end }}
{{- $versionDNSNormalized := replace "." "-dot-" $version }}

{{- $versionURLNormalized := "" }}
{{- if eq $version "main" }}
{{- $versionURLNormalized = "latest" }}
{{- else }}
{{- $versionURLNormalized = $version }}
{{- end }}

{{- $host := pluck $.Values.werf.env $.Values.host | first | default $.Values.host._default  }}
{{- if eq $.Values.werf.env "production" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Original-URI $request_uri;
      ssi on;
      ssi_silent_errors on;
{{ include "rewrites" $ | indent 6 }}
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: {{ include "ingressClassName" $ }}
  tls:
  - hosts:
      - ru.{{ $host }}
      - {{ $host }}
      - www.{{ $host }}
    secretName: tls-werf-io
  rules:
  - host: ru.{{ $host }}
    http:
      paths:
      - path: /docs/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
      - path: /documentation/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
  - host: {{ $host }}
    http:
      paths:
      - path: /docs/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
      - path: /documentation/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
{{- else }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Original-URI $request_uri;
      ssi on;
      ssi_silent_errors on;
{{ include "rewrites" $ | indent 6 }}
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
    nginx.ingress.kubernetes.io/auth-signin: https://$host/dex-authenticator/sign_in
    nginx.ingress.kubernetes.io/auth-url: https://werfio-dex-authenticator.{{ $.Values.werf.namespace }}.svc.cluster.local/dex-authenticator/auth
spec:
  ingressClassName: {{ include "ingressClassName" $ }}
  tls:
  - hosts:
      - {{ $host }}
    secretName: {{ pluck $.Values.werf.env $.Values.ingressSecretName | first | default $.Values.ingressSecretName._default }}
  rules:
  - host: {{ $host }}
    http:
      paths:
      - path: /docs/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
      - path: /documentation/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Chart.Name }}-ru-{{ $versionDNSNormalized }}
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Original-URI $request_uri;
      ssi on;
      ssi_silent_errors on;
{{ include "rewrites" $ | indent 6 }}
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User,X-Auth-Request-Email
    nginx.ingress.kubernetes.io/auth-signin: https://ru-{{ $host }}/dex-authenticator/sign_in
    nginx.ingress.kubernetes.io/auth-url: https://werfio-ru-dex-authenticator.{{ $.Values.werf.namespace }}.svc.cluster.local/dex-authenticator/auth
spec:
  ingressClassName: {{ include "ingressClassName" $ }}
  tls:
  - hosts:
      - ru-{{ $host }}
    secretName: {{ pluck $.Values.werf.env $.Values.ingressSecretName | first | default $.Values.ingressSecretName._default }}
  rules:
  - host: ru-{{ $host }}
    http:
      paths:
      - path: /docs/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
      - path: /documentation/{{ $versionURLNormalized }}/
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $.Chart.Name }}-{{ $versionDNSNormalized }}
            port:
              name: http
{{- end }}

{{- end }}
