name: Get commit message
description: Gets message from commit (and PR)

outputs:
  message:
    description: "Commit message"
    value: ${{ steps.get_commit_message.outputs.message }}
inputs:
  ignoreTitle:
    description: 'Setting this input to true will exclude the Pull Request title.'
    required: false
    default: 'true'
  ignoreDescription:
    description: 'Setting this input to true will exclude the Pull Request description.'
    required: false
    default: 'true'
  ignoreLatestCommitMessage:
    description: 'Setting this input to true will esclude latest commit message'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Retrieve
      uses: actions/github-script@v5.0.0
      id: get_commit_message
      env:
        ignoreTitle: ${{ inputs.ignoreTitle }}
        ignoreDescription: ${{ inputs.ignoreDescription }}
        ignoreLatestCommitMessage: ${{ inputs.ignoreLatestCommitMessage }}
      with:
        script: |
          const script = require('./.github/scripts/get-commit-mesage.js');
          return await script.run({ github, context, core });
