// Code generated by "stringer -type=ArchiveType"; DO NOT EDIT.

package container_backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FileArchive-0]
	_ = x[DirectoryArchive-1]
}

const _ArchiveType_name = "FileArchiveDirectoryArchive"

var _ArchiveType_index = [...]uint8{0, 11, 27}

func (i ArchiveType) String() string {
	if i < 0 || i >= ArchiveType(len(_ArchiveType_index)-1) {
		return "ArchiveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ArchiveType_name[_ArchiveType_index[i]:_ArchiveType_index[i+1]]
}
