// Code generated by "stringer -type=RemoveType"; DO NOT EDIT.

package container_backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RemoveExactPath-0]
	_ = x[RemoveExactPathWithEmptyParentDirs-1]
	_ = x[RemoveInsidePath-2]
}

const _RemoveType_name = "RemoveExactPathRemoveExactPathWithEmptyParentDirsRemoveInsidePath"

var _RemoveType_index = [...]uint8{0, 15, 49, 65}

func (i RemoveType) String() string {
	if i < 0 || i >= RemoveType(len(_RemoveType_index)-1) {
		return "RemoveType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RemoveType_name[_RemoveType_index[i]:_RemoveType_index[i+1]]
}
