// Code generated by "stringer -type=StapelStageType"; DO NOT EDIT.

package container_backend

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FromStage-0]
	_ = x[UserCommandsStage-1]
	_ = x[DockerInstructionsStage-2]
}

const _StapelStageType_name = "FromStageUserCommandsStageDockerInstructionsStage"

var _StapelStageType_index = [...]uint8{0, 9, 26, 49}

func (i StapelStageType) String() string {
	if i < 0 || i >= StapelStageType(len(_StapelStageType_index)-1) {
		return "StapelStageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StapelStageType_name[_StapelStageType_index[i]:_StapelStageType_index[i+1]]
}
