source 'https://supermarket.chef.io'

cookbook 'test', path: '.'
cookbook 'mdapp-test', path: '../mdapp-test'
cookbook 'mdapp-test2', path: '../mdapp-test2'
cookbook 'mdapp-testartifact', path: '../mdapp-testartifact'

cookbook 'apt'
