package root

import (
	"path/filepath"
	"strings"
	"sync/atomic"

	"github.com/onsi/ginkgo/v2"
	"github.com/onsi/gomega"
	"sigs.k8s.io/yaml"
)

var _ = ginkgo.Describe("optional Docker backend", func() {
	ginkgo.DescribeTable("ComponentsManager preserves optional daemon settings behavior", func(version string, pingStatus, infoStatus int, expected string, succeeds bool) {
		host, requests := settingsDaemon(version, pingStatus, infoStatus)
		stdout, stderr, code := dockerCommand(dockerProject(false), host, "components")
		gomega.Expect(requests.Load()).To(gomega.BeNumerically(">", 0))
		if succeeds {
			gomega.Expect(code).To(gomega.BeZero(), "%s", stderr)
			gomega.Expect(stdout).To(gomega.ContainSubstring(expected))
		} else {
			gomega.Expect(code).To(gomega.Equal(1))
			gomega.Expect(stderr).To(gomega.ContainSubstring(expected))
		}
	},
		ginkgo.Entry("old API is optional", "1.39", 200, 200, "mirrors: []", true),
		ginkgo.Entry("supported API supplies mirrors", "1.40", 200, 200, "https://mirror.example", true),
		ginkgo.Entry("settings authentication propagates", "1.40", 200, 401, "settings denied", false),
		ginkgo.Entry("old API does not hide ping authentication", "1.39", 401, 200, "ping denied", false),
		ginkgo.Entry("old API does not hide unexpected ping failure", "1.39", 500, 200, "ping denied", false),
	)

	for _, command := range []string{"plan", "lint", "helm get-autogenerated-values", "bundle publish"} {
		ginkgo.Describe(command, func() {
			ginkgo.DescribeTable("chart paths do not contact Docker", func(daemonMode, imageMode string) {
				var host string
				requests := &atomic.Int32{}
				switch daemonMode {
				case "old":
					host, requests = settingsDaemon("1.39", 200, 200)
				case "mute":
					host, requests = muteDaemon()
				case "absent":
					host = "unix://" + filepath.Join(ginkgo.GinkgoT().TempDir(), "absent.sock")
				}
				dir := dockerProject(imageMode != "no-images")
				args := strings.Fields(command)
				if imageMode == "without-images" {
					args = append(args, "--without-images")
				}
				if command == "plan" {
					args = append(args, "--kube-config", planKubeConfig())
				}
				if command == "bundle publish" {
					server, _ := authenticatedRegistry(dir)
					args = append(args, "--repo", strings.TrimPrefix(server.URL, "http://")+"/bundle", "--insecure-registry")
				}
				stdout, stderr, code := dockerCommand(dir, host, args...)
				gomega.Expect(requests.Load()).To(gomega.BeZero(), "stdout: %s\nstderr: %s", stdout, stderr)
				gomega.Expect(code).To(gomega.BeZero(), "stdout: %s\nstderr: %s", stdout, stderr)

				if command == "helm get-autogenerated-values" {
					var values map[string]any
					gomega.Expect(yaml.Unmarshal([]byte(stdout), &values)).To(gomega.Succeed())
					gomega.Expect(values).To(gomega.HaveKey("werf"))
				}
			},
				ginkgo.Entry("old daemon, no images", "old", "no-images"),
				ginkgo.Entry("absent daemon, no images", "absent", "no-images"),
				ginkgo.Entry("mute daemon, no images", "mute", "no-images"),
				ginkgo.Entry("old daemon, images excluded", "old", "without-images"),
			)

			if command != "bundle publish" {
				ginkgo.DescribeTable("stub paths do not contact Docker", func(stubTags bool) {
					host, requests := settingsDaemon("1.39", 200, 200)
					dir := dockerProject(true)
					args := strings.Fields(command)
					if stubTags {
						args = append(args, "--stub-tags", "--repo=example.com/images")
					}
					if command == "plan" {
						args = append(args, "--kube-config", planKubeConfig())
					}
					stdout, stderr, code := dockerCommand(dir, host, args...)
					gomega.Expect(requests.Load()).To(gomega.BeZero(), "%s\n%s", stdout, stderr)
					gomega.Expect(code).To(gomega.BeZero(), "%s\n%s", stdout, stderr)
				}, ginkgo.Entry("explicit stub tags", true), ginkgo.Entry("local repository", false))
			}

			if command == "lint" || command == "plan" {
				ginkgo.It("loads private OCI dependencies with custom Docker credentials", func() {
					dir := dockerProject(false)
					server, authenticated := authenticatedRegistry(dir)
					addOCIDependency(dir, server.URL)
					before := authenticated.Load()
					host, requests := settingsDaemon("1.39", 200, 200)
					args := append(strings.Fields(command), "--insecure-helm-dependencies")
					if command == "plan" {
						args = append(args, "--kube-config", planKubeConfig())
					}
					stdout, stderr, code := dockerCommand(dir, host, args...)
					gomega.Expect(code).To(gomega.BeZero(), "%s\n%s", stdout, stderr)
					gomega.Expect(authenticated.Load()).To(gomega.BeNumerically(">", before))
					gomega.Expect(requests.Load()).To(gomega.BeZero())
				})
			}

			if command == "bundle publish" {
				ginkgo.It("publishes a chart-only bundle into the authenticated final repo", func() {
					dir := dockerProject(false)
					server, authenticated := authenticatedRegistry(dir)
					before := authenticated.Load()
					host := "unix://" + filepath.Join(ginkgo.GinkgoT().TempDir(), "absent.sock")
					stdout, stderr, code := dockerCommand(dir, host, "bundle", "publish",
						"--repo", "127.0.0.1:1/unreachable",
						"--final-repo", strings.TrimPrefix(server.URL, "http://")+"/bundle",
						"--insecure-registry")
					gomega.Expect(code).To(gomega.BeZero(), "stdout: %s\nstderr: %s", stdout, stderr)
					gomega.Expect(authenticated.Load()).To(gomega.BeNumerically(">", before))
				})

				ginkgo.It("requires a repo for a chart-only bundle", func() {
					host := "unix://" + filepath.Join(ginkgo.GinkgoT().TempDir(), "absent.sock")
					_, stderr, code := dockerCommand(dockerProject(false), host, "bundle", "publish")
					gomega.Expect(code).To(gomega.Equal(1))
					gomega.Expect(stderr).To(gomega.ContainSubstring("--repo=ADDRESS param required"))
				})

				ginkgo.DescribeTable("rejects an unsupported container registry of a chart-only bundle repo", func(flag string) {
					host := "unix://" + filepath.Join(ginkgo.GinkgoT().TempDir(), "absent.sock")
					_, stderr, code := dockerCommand(dockerProject(false), host, "bundle", "publish",
						"--repo", "example.com/images", "--final-repo", "example.com/bundle", flag, "bogus")
					gomega.Expect(code).To(gomega.Equal(1))
					gomega.Expect(stderr).To(gomega.ContainSubstring(`container registry "bogus" is not supported`))
				},
					ginkgo.Entry("primary repo", "--repo-container-registry"),
					ginkgo.Entry("final repo", "--final-repo-container-registry"),
				)
			}

			ginkgo.DescribeTable("image paths retain the daemon gate", func(mute bool) {
				host, requests := settingsDaemon("1.39", 200, 200)
				expected := "minimum supported API version is 1.40"
				if mute {
					host, requests = muteDaemon()
					expected = "Docker daemon did not answer within 10s"
				}
				args := append(strings.Fields(command), "--repo=example.com/images")
				_, stderr, code := dockerCommand(dockerProject(true), host, args...)
				gomega.Expect(requests.Load()).To(gomega.BeNumerically(">", 0))
				gomega.Expect(code).To(gomega.Equal(1))
				gomega.Expect(stderr).To(gomega.ContainSubstring(expected))
			},
				ginkgo.Entry("rejects old daemon", false),
				ginkgo.Entry("rejects mute daemon", true),
			)
		})
	}
})
