package helm

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/werf/logboek"
	"github.com/werf/logboek/pkg/level"

	"github.com/werf/werf/cmd/werf/common"
	helm_common "github.com/werf/werf/cmd/werf/helm/common"
	"github.com/werf/werf/pkg/deploy"
	"github.com/werf/werf/pkg/docker"
	"github.com/werf/werf/pkg/image"
	"github.com/werf/werf/pkg/ssh_agent"
	"github.com/werf/werf/pkg/true_git"
	"github.com/werf/werf/pkg/util"
	"github.com/werf/werf/pkg/werf"
)

var getAutogeneratedValuesCmdData common.CmdData

func NewGetAutogeneratedValuesCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get-autogenerated-values",
		Short: "Get service values yaml generated by werf for helm chart during deploy",
		Long: common.GetLongCommandDescription(`Get service values generated by werf for helm chart during deploy.

These values includes project name, docker images ids and other`),
		DisableFlagsInUseLine: true,
		Annotations: map[string]string{
			common.CmdEnvAnno: common.EnvsDescription(common.WerfSecretKey),
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			if err := common.ProcessLogOptions(&getAutogeneratedValuesCmdData); err != nil {
				common.PrintHelp(cmd)
				return err
			}

			return runGetServiceValues()
		},
	}

	common.SetupDir(&getAutogeneratedValuesCmdData, cmd)
	common.SetupConfigPath(&getAutogeneratedValuesCmdData, cmd)
	common.SetupConfigTemplatesDir(&getAutogeneratedValuesCmdData, cmd)
	common.SetupTmpDir(&getAutogeneratedValuesCmdData, cmd)
	common.SetupHomeDir(&getAutogeneratedValuesCmdData, cmd)
	common.SetupSSHKey(&getAutogeneratedValuesCmdData, cmd)

	common.SetupEnvironment(&getAutogeneratedValuesCmdData, cmd)
	common.SetupNamespace(&getAutogeneratedValuesCmdData, cmd)

	common.SetupDockerConfig(&getAutogeneratedValuesCmdData, cmd, "Command needs granted permissions to read and pull images from the specified stages storage and images repo")
	common.SetupInsecureRegistry(&getAutogeneratedValuesCmdData, cmd)
	common.SetupSkipTlsVerifyRegistry(&getAutogeneratedValuesCmdData, cmd)

	common.SetupLogOptions(&getAutogeneratedValuesCmdData, cmd)

	return cmd
}

func runGetServiceValues() error {
	logboek.SetAcceptedLevel(level.Error)

	ctx := common.BackgroundContext()

	if err := werf.Init(*getAutogeneratedValuesCmdData.TmpDir, *getAutogeneratedValuesCmdData.HomeDir); err != nil {
		return fmt.Errorf("initialization error: %s", err)
	}

	if err := image.Init(); err != nil {
		return err
	}

	if err := true_git.Init(true_git.Options{LiveGitOutput: *getAutogeneratedValuesCmdData.LogVerbose || *getAutogeneratedValuesCmdData.LogDebug}); err != nil {
		return err
	}

	if err := common.DockerRegistryInit(&getAutogeneratedValuesCmdData); err != nil {
		return err
	}

	if err := docker.Init(ctx, *getAutogeneratedValuesCmdData.DockerConfig, *getAutogeneratedValuesCmdData.LogVerbose, *getAutogeneratedValuesCmdData.LogDebug); err != nil {
		return err
	}

	ctxWithDockerCli, err := docker.NewContext(ctx)
	if err != nil {
		return err
	}
	ctx = ctxWithDockerCli

	projectDir, err := common.GetProjectDir(&getAutogeneratedValuesCmdData)
	if err != nil {
		return fmt.Errorf("getting project dir failed: %s", err)
	}

	werfConfig, err := common.GetRequiredWerfConfig(ctx, projectDir, &getAutogeneratedValuesCmdData, false)
	if err != nil {
		return fmt.Errorf("unable to load werf config: %s", err)
	}

	projectName := werfConfig.Meta.Project

	environment := helm_common.GetEnvironmentOrStub(*getAutogeneratedValuesCmdData.Environment)

	namespace, err := common.GetKubernetesNamespace(*getAutogeneratedValuesCmdData.Namespace, environment, werfConfig)
	if err != nil {
		return err
	}

	if err := ssh_agent.Init(ctx, *getAutogeneratedValuesCmdData.SSHKeys); err != nil {
		return fmt.Errorf("cannot initialize ssh agent: %s", err)
	}
	defer func() {
		err := ssh_agent.Terminate()
		if err != nil {
			logboek.Error().LogF("WARNING: ssh agent termination failed: %s\n", err)
		}
	}()

	imagesInfoGetters := common.StubImageInfoGetters(werfConfig)

	serviceValues, err := deploy.GetServiceValues(ctx, projectName, common.StubRepoAddress, namespace, imagesInfoGetters, deploy.ServiceValuesOptions{Env: environment})
	if err != nil {
		return fmt.Errorf("error creating service values: %s", err)
	}

	fmt.Printf("%s", util.DumpYaml(serviceValues))

	return nil
}
