package helm

import (
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/samber/lo"
	"github.com/spf13/cobra"

	"github.com/werf/nelm/pkg/action"
	helmcmd "github.com/werf/nelm/pkg/helm/pkg/cmd"
	"github.com/werf/nelm/pkg/log"
	"github.com/werf/werf/v2/cmd/werf/common"
	helm_secret_decrypt "github.com/werf/werf/v2/cmd/werf/helm/secret/decrypt"
	helm_secret_encrypt "github.com/werf/werf/v2/cmd/werf/helm/secret/encrypt"
	helm_secret_file_decrypt "github.com/werf/werf/v2/cmd/werf/helm/secret/file/decrypt"
	helm_secret_file_edit "github.com/werf/werf/v2/cmd/werf/helm/secret/file/edit"
	helm_secret_file_encrypt "github.com/werf/werf/v2/cmd/werf/helm/secret/file/encrypt"
	helm_secret_generate_secret_key "github.com/werf/werf/v2/cmd/werf/helm/secret/generate_secret_key"
	helm_secret_rotate_secret_key "github.com/werf/werf/v2/cmd/werf/helm/secret/rotate_secret_key"
	helm_secret_values_decrypt "github.com/werf/werf/v2/cmd/werf/helm/secret/values/decrypt"
	helm_secret_values_edit "github.com/werf/werf/v2/cmd/werf/helm/secret/values/edit"
	helm_secret_values_encrypt "github.com/werf/werf/v2/cmd/werf/helm/secret/values/encrypt"
	"github.com/werf/werf/v2/pkg/werf"
)

var _commonCmdData common.CmdData

func NewCmd(ctx context.Context) (*cobra.Command, error) {
	ctx = common.NewContextWithCmdData(ctx, &_commonCmdData)
	cmd := common.SetCommandContext(ctx, &cobra.Command{
		Use:          "helm",
		Short:        "Manage application deployment with helm",
		SilenceUsage: true,
	})

	common.SetupTmpDir(&_commonCmdData, cmd, common.SetupTmpDirOptions{})
	common.SetupHomeDir(&_commonCmdData, cmd, common.SetupHomeDirOptions{})
	common.SetupLogOptions(&_commonCmdData, cmd)

	// FIXME(major): add missing werf get/history/list commands
	// FIXME(major): restore werf/nelm/cmd/create.go

	helmRootCmd, err := helmcmd.NewRootCmd(os.Stdout, os.Args[1:], helmcmd.SetupLogging)
	if err != nil {
		return nil, fmt.Errorf("init helm: %w", err)
	}

	cmd.AddCommand(
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "create")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "dependency")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "repo")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "env")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "package")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "pull")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "search")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "show")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "verify")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "version")
		})),
		lo.Must(lo.Find(helmRootCmd.Commands(), func(c *cobra.Command) bool {
			return strings.HasPrefix(c.Use, "registry")
		})),
	)

	overrideRunE(ctx, cmd)

	cmd.AddCommand(
		secretCmd(ctx),
		NewGetAutogeneratedValuesCmd(ctx),
		NewGetNamespaceCmd(ctx),
		NewGetReleaseCmd(ctx),
	)

	return cmd, nil
}

func secretCmd(ctx context.Context) *cobra.Command {
	cmd := common.SetCommandContext(ctx, &cobra.Command{
		Use:   "secret",
		Short: "Work with secrets",
	})

	fileCmd := common.SetCommandContext(ctx, &cobra.Command{
		Use:   "file",
		Short: "Work with secret files",
	})

	fileCmd.AddCommand(
		helm_secret_file_encrypt.NewCmd(ctx),
		helm_secret_file_decrypt.NewCmd(ctx),
		helm_secret_file_edit.NewCmd(ctx),
	)

	valuesCmd := common.SetCommandContext(ctx, &cobra.Command{
		Use:   "values",
		Short: "Work with secret values files",
	})

	valuesCmd.AddCommand(
		helm_secret_values_encrypt.NewCmd(ctx),
		helm_secret_values_decrypt.NewCmd(ctx),
		helm_secret_values_edit.NewCmd(ctx),
	)

	cmd.AddCommand(
		fileCmd,
		valuesCmd,
		helm_secret_generate_secret_key.NewCmd(ctx),
		helm_secret_encrypt.NewCmd(ctx),
		helm_secret_decrypt.NewCmd(ctx),
		helm_secret_rotate_secret_key.NewCmd(ctx),
	)

	return cmd
}

func overrideRunE(ctx context.Context, cmd *cobra.Command) {
	if !cmd.Runnable() {
		return
	}

	oldRunE := cmd.RunE
	cmd.RunE = func(cmd *cobra.Command, args []string) error {
		helmSettings := helmcmd.Settings

		ctx := action.SetupLogging(ctx, lo.Ternary(helmSettings.Debug, log.DebugLevel, log.InfoLevel), action.SetupLoggingOptions{
			ColorMode: log.LogColorModeOff,
		})
		cmd.SetContext(ctx)

		if err := werf.Init(*_commonCmdData.TmpDir, *_commonCmdData.HomeDir); err != nil {
			return err
		}

		return oldRunE(cmd, args)
	}

	for _, c := range cmd.Commands() {
		overrideRunE(ctx, c)
	}
}
