module Dapp
  module GitRepo
    # Gitkeeper for autogenerated and external data
    class Chronicler < Base
      def initialize(application, name)
        super

        unless File.directory? chronodir_path
          git "init --separate-git-dir=#{dir_path} #{chronodir_path}"
          git_chrono 'commit --allow-empty -m init'
        end
      end

      def chronodir_path(*path)
        application.build_path name, *path
      end

      def commit!(comment = '+')
        git_chrono 'add --all'
        unless git_chrono('diff --cached --quiet', returns: [0, 1]).status.success?
          git_chrono "commit -m #{comment}"
        end
      end

      def cleanup!
        super
        FileUtils.rm_rf dir_path
        FileUtils.rm_rf chronodir_path
      end

      protected

      def git_chrono(command, **kwargs)
        git "-C #{chronodir_path} #{command}", **kwargs
      end
    end
  end
end
