source "https://rubygems.org"

gem "jekyll-assets", git: "https://github.com/envygeeks/jekyll-assets", group: :jekyll_plugins
gem "jekyll", ">= 3.5", "< 5.0"
gem 'html-proofer', '~> 3.3'
gem "kramdown-parser-gfm"
gem "jekyll-include-cache", "~> 0.2"
# Can't use jekyll-sass-converter "~> 3.0" in alpine based images: https://github.com/sass/dart-sass-embedded/issues/106#issuecomment-1374950950
gem "jekyll-sass-converter", "~> 3.0"

gem "sprockets", "~> 4.2"
gem "nokogiri", ">= 1.12.5"
gem "kramdown", ">= 2.3.0"
