name: xxxxx(internal)

on:
  workflow_call:

jobs:
  _:
    runs-on: delivery-github-runner
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          cache: false
          go-version-file: go.mod

      - name: Build
        run: task --yes build:dev:linux:amd64
        env:
          TASK_X_REMOTE_TASKFILES: 1
