name: xxxxx(internal)

on:
  workflow_call:
    inputs:
      checkoutRef:
        required: false
        default: ""
        type: string
      env:
        required: true
        type: string
      githubRefOverride:
        required: false
        default: ""
        type: string
      persistent:
        default: false
        type: boolean
      runner:
        default: ubuntu-22.04
        type: string
    secrets:
      kubeConfig:
        required: true

defaults:
  run:
    shell: bash

jobs:
  _:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkoutRef != '' && inputs.checkoutRef || github.ref }}

      - name: Set dynamic WERF_* env vars
        run: |
          github_ref_override='${{ inputs.githubRefOverride }}'

          if ${{ inputs.persistent }}; then
            pr_number='${{ github.event.pull_request.number }}'
            if [[ -n "$github_ref_override" ]]; then
              github_ref_value="$github_ref_override"
            elif [[ -n "$pr_number" ]]; then
              github_ref_value="pr-${pr_number}"
            else
              github_ref_value='${{ github.ref }}'
            fi

            if [[ -n "$github_ref_override" ]]; then
              release_ref_value="$github_ref_override"
            else
              release_ref_source='${{ github.ref }}'
              release_ref_value="$(echo "$release_ref_source" | cut -d/ -f 3)"
              if [[ -z "$release_ref_value" ]]; then
                release_ref_value="$release_ref_source"
              fi
            fi

            release_ref_value="$(echo "$release_ref_value" | sed 's/\+/-plus-/g' | sed 's/\_/-u-/g' | sed 's/\./-dot-/g' | sed 's#/#-#g')"

            cat >> "$GITHUB_ENV" <<EOF
          WERF_RELEASE=werfio-${release_ref_value}-${{ inputs.env }}
          WERF_SET_GITHUB_REF=global.github_ref=$github_ref_value
          EOF
          else
            cat >> "$GITHUB_ENV" <<EOF
          WERF_RELEASE=werfio-documentation-${{ inputs.env }}
          WERF_SET_GITHUB_REF=global.github_ref=main
          EOF
          fi

      - name: Install werf
        uses: werf/actions/install@v2

      - name: Deploy
        run: |
          . $(werf ci-env github --as-file)
          werf converge --virtual-merge=false
        env:
          WERF_NAMESPACE: werfio-${{ inputs.env }}
          WERF_DIR: docs
          WERF_LOG_VERBOSE: on
          WERF_REPO: ghcr.io/${{ github.repository_owner }}/werfio
          WERF_ENV: ${{ inputs.env }}
          WERF_KUBE_CONFIG_BASE64: ${{ secrets.kubeConfig }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
