name: xxxxx(internal)

on:
  workflow_call:
    inputs:
      linuxAmd64Runner:
        default: ubuntu-22.04
        type: string

defaults:
  run:
    shell: bash

jobs:
  _:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ${{ inputs.linuxAmd64Runner }}
        cr:
          #          - default
          - ecr
          - github
          - harbor
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    env:
      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_ACR: 0
      WERF_TEST_ACR_PASSWORD: ${{ secrets.WERF_TEST_ACR_PASSWORD }}
      WERF_TEST_ACR_REGISTRY: ${{ secrets.WERF_TEST_ACR_REGISTRY }}
      WERF_TEST_ACR_USERNAME: ${{ secrets.WERF_TEST_ACR_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_DEFAULT: 0
      WERF_TEST_DEFAULT_PASSWORD: ${{ secrets.WERF_TEST_DEFAULT_PASSWORD }}
      WERF_TEST_DEFAULT_REGISTRY: ${{ secrets.WERF_TEST_DEFAULT_REGISTRY }}
      WERF_TEST_DEFAULT_USERNAME: ${{ secrets.WERF_TEST_DEFAULT_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_DOCKERHUB: 0
      WERF_TEST_DOCKERHUB_PASSWORD: ${{ secrets.WERF_TEST_DOCKERHUB_PASSWORD }}
      WERF_TEST_DOCKERHUB_REGISTRY: ${{ secrets.WERF_TEST_DOCKERHUB_REGISTRY }}
      WERF_TEST_DOCKERHUB_USERNAME: ${{ secrets.WERF_TEST_DOCKERHUB_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_ECR: 1
      WERF_TEST_ECR_REGISTRY: ${{ secrets.WERF_TEST_ECR_REGISTRY }}
      WERF_TEST_ECR_PASSWORD: ${{ secrets.WERF_TEST_ECR_PASSWORD }}
      WERF_TEST_ECR_USERNAME: ${{ secrets.WERF_TEST_ECR_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_GITHUB: 1
      WERF_TEST_GITHUB_PASSWORD: ${{ secrets.WERF_TEST_GITHUB_PASSWORD }}
      WERF_TEST_GITHUB_REGISTRY: ${{ secrets.WERF_TEST_GITHUB_REGISTRY }}
      WERF_TEST_GITHUB_TOKEN: ${{ secrets.WERF_TEST_GITHUB_TOKEN }}
      WERF_TEST_GITHUB_USERNAME: ${{ secrets.WERF_TEST_GITHUB_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_HARBOR: 1
      WERF_TEST_HARBOR_PASSWORD: ${{ secrets.WERF_TEST_HARBOR_PASSWORD }}
      WERF_TEST_HARBOR_REGISTRY: ${{ secrets.WERF_TEST_HARBOR_REGISTRY }}
      WERF_TEST_HARBOR_USERNAME: ${{ secrets.WERF_TEST_HARBOR_USERNAME }}

      WERF_TEST_DOCKER_REGISTRY_IMPLEMENTATION_QUAY: 0
      WERF_TEST_QUAY_PASSWORD: ${{ secrets.WERF_TEST_QUAY_PASSWORD }}
      WERF_TEST_QUAY_REGISTRY: ${{ secrets.WERF_TEST_QUAY_REGISTRY }}
      WERF_TEST_QUAY_TOKEN: ${{ secrets.WERF_TEST_QUAY_TOKEN }}
      WERF_TEST_QUAY_USERNAME: ${{ secrets.WERF_TEST_QUAY_USERNAME }}
    steps:
      - name: Install werf build dependencies
        run: sudo apt-get install -y libbtrfs-dev

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          cache: true
          go-version-file: go.mod

      - name: Install Task
        uses: go-task/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - if: matrix.cr == 'acr'
        name: Login to ACR
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - if: matrix.cr == 'ecr'
        name: Login to ECR
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install ginkgo
        run: task --yes -p deps:install:ginkgo

      - name: Check container registry creds
        run: ./scripts/ci/integration_tests_registries_login.sh ${{ matrix.cr }}

      - name: Test
        run: |
          task --yes -p test:e2e paths="test/e2e/container_registry" -- --focus="\[${{ matrix.cr }}\]" --flake-attempts=3 --keep-going
          echo loadavg: $(cat /proc/loadavg)
