name: cleanup:werf-storage
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  cleanup:
    name: cleanup werf-storage
    runs-on: ubuntu-latest-16-cores
    strategy:
      matrix:
        config:
          - --config werf.yaml
          - --config werf-argocd-cmp-sidecar.yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install werf
        uses: werf/actions/install@v2
        with:
          channel: alpha

      - name: Cleanup
        run: |
          cd scripts/werf-in-image/
          . $(werf ci-env github --as-file)
          werf cleanup ${{ matrix.config }}
        env:
          WERF_REPO: ghcr.io/werf/werf-storage
          WERF_REPO_GITHUB_TOKEN: ${{ secrets.WERF_IN_IMAGE_CLEANUP_GHCR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WERF_WITHOUT_KUBE: true
