name: Do release PR or GitHub release
on:
  push:
    branches:
    - "main"
    - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - uses: werf/third-party-release-please-action@werf
      with:
        default-branch: ${{ steps.extract_branch.outputs.branch }}
        release-type: go
        bump-minor-pre-major: true
        bump-patch-for-minor-pre-major: true
        token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        release-notes-header: "## Changelog"
        release-notes-footer: |
          ## Installation

          To install `werf` we strongly recommend following [these instructions](https://werf.io/installation.html).

          Alternatively, you can download `werf` binaries from here:
          * [Linux amd64](https://tuf.werf.io/targets/releases/{{> version }}/linux-amd64/bin/werf) ([PGP signature](https://tuf.werf.io/targets/signatures/{{> version }}/linux-amd64/bin/werf.sig))
          * [Linux arm64](https://tuf.werf.io/targets/releases/{{> version }}/linux-arm64/bin/werf) ([PGP signature](https://tuf.werf.io/targets/signatures/{{> version }}/linux-arm64/bin/werf.sig))
          * [macOS amd64](https://tuf.werf.io/targets/releases/{{> version }}/darwin-amd64/bin/werf) ([PGP signature](https://tuf.werf.io/targets/signatures/{{> version }}/darwin-amd64/bin/werf.sig))
          * [macOS arm64](https://tuf.werf.io/targets/releases/{{> version }}/darwin-arm64/bin/werf) ([PGP signature](https://tuf.werf.io/targets/signatures/{{> version }}/darwin-arm64/bin/werf.sig))
          * [Windows amd64](https://tuf.werf.io/targets/releases/{{> version }}/windows-amd64/bin/werf.exe) ([PGP signature](https://tuf.werf.io/targets/signatures/{{> version }}/windows-amd64/bin/werf.exe.sig))

          These binaries were signed with PGP and could be verified with the [werf PGP public key](https://werf.io/werf.asc). For example, `werf` binary can be downloaded and verified with `gpg` on Linux with these commands:
          ```shell
          curl -sSLO "https://tuf.werf.io/targets/releases/{{> version }}/linux-amd64/bin/werf" -O "https://tuf.werf.io/targets/signatures/{{> version }}/linux-amd64/bin/werf.sig"
          curl -sSL https://werf.io/werf.asc | gpg --import
          gpg --verify werf.sig werf
          ```
