name: Website Deployment
on:
  push:
    branches:
      - multiwerf
    paths:
      - trdl_channels.yaml

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Deploy website to production
      run: |
        curl -X POST \
             -F "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
             -F "ref=master" \
             ${{ secrets.GITLAB_URL }}/api/v4/projects/${{ secrets.GITLAB_PROJECT_ID }}/trigger/pipeline
